<?php
if(RNI_API_PRODUCTION){
    define('RNI_API_COMPANY_ID',18);
    define('RNI_API_ACCESS_TOKEN','eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55X2lkIjoxOCwidXNlcm5hbWUiOiJiZ3IiLCJkYXRlIjoiMjAyMS0xMC0yNiAxNDoxNTo0NiJ9.GHuYqxwLoJfoz-QZkKyOePo_XyVvJG3BhJQc47PNNf4');
}else{
    define('RNI_API_COMPANY_ID',18);
    define('RNI_API_ACCESS_TOKEN','eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb21wYW55X2lkIjoxOCwidXNlcm5hbWUiOiJiZ3IiLCJkYXRlIjoiMjAyMS0xMC0yNiAxNDoxNTo0NiJ9.GHuYqxwLoJfoz-QZkKyOePo_XyVvJG3BhJQc47PNNf4');
}